### PR TITLE
Update essex_hog.rs

### PR DESCRIPTION
**Pull request by alaaseeku**
allow connection to on-perm Confluence by removing encoding token

### CODE REVIEW

**Comment by cutler-scott-newrelic** [comment]
Hi @alaaseeku ! Since I don't seem to be able to use this authentication method on my confluence, can you point me to the Atlassian documentation around this specific type of key? And/or show me a screenshot of it working on your instance? I know there is at least one other person using this argument so I don't want to make a breaking change unless I can confirm it's working. Though in general I think this change makes sense.

**Comment by Spencer-Doak** [comment]
Howdy, @cutler-scott-newrelic I just want to confirm that encoding Confluence tokens for on-prem servers (e.g., Confluence Data Center) is incorrect behavior. Here's some documentation which essentially says personal access tokens should be passed without any transformations/modifications: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

Hope that helps! I am planning to test out Rusty Hog soon to scan for secrets in a Confluence Data Center server along with a few other sources, so when I saw this PR, I figured I'd chime in.

**Comment by Spencer-Doak** [comment]
A quick follow-up: I tested out Rusty Hog a couple months ago. As expected, Rusty Hog's master branch failed to scan a Confluence Data Center server. After locally merging @alaaseeku's commit into my clone of the Rusty Hog repo & rebuilding, my Confluence scans succeeded.

@cutler-scott-newrelic please merge this change so I don't have to maintain a fork 🙏

**Comment by cutler-scott-newrelic** [comment]
Sorry for making you all bug me over the last 2 years. Since I have
confirmation someone else tested it successfully, I'll merge it tomorrow!

**Pull request merged**
