### PR TITLE
Move SecretScanner to its own crate

### PR DESCRIPTION
**Pull request by raulcabello**
Move `SecretScanner` into a different crate `rusty-hog-scanner`. Use cargo workspaces to import this new crate. This way the scanner can be easily used in other projects without having to import all the other functionality such as git or s3 secrets reader. This also makes it possible to compile the `rusty-hog-scanner` to wasm modules.

Fixes https://github.com/newrelic/rusty-hog/issues/44

### CODE REVIEW

**Comment by flavio** [comment]
Some background on why we are interested about that. We are maintainers of the [kubewarden](https://kubewarden.io) policy engine for Kubernetes (a CNCF sandbox project).

We would like to leverage this library to write an admission policy that prevents the creation of containers that leak sensitive data.
We found rusty-hog to be perfect for this use case :smile:

**Comment by cutler-scott-newrelic** [comment]
This sounds like a great idea! I'm going to spend some time in my next sprint (next week) to make sure it doesn't cause any issues with our existing tooling, make sure it passes tests, etc., then I'll merge it in. In the mean-time, can you do a git pull on the PR branch to catch up with the other PR I just merged in?

**Comment by raulcabello** [comment]
Thanks for looking into this! I have just updated the PR with the latest changes from master

**Comment by cutler-scott-newrelic** [comment]
I'm going to work on fixing the imports in the tests now that it's merged in. FYI, until someone tackles GitHub actions I'm not worrying about formal releases, so you'll just have to clone from master (or whatever tag you choose to settle on).

**Pull request merged**
