### PR TITLE
Extend the scanner to allow entropy threshold definition per pattern

### PR DESCRIPTION
**Pull request by ccojocar**
Extend the pattern definition to allow entropy threshold definition also for patterns such as:
```JSON
{
    "Slack Token": { 
        "pattern": "(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})",
        "entropy": true,
        "threshold": "4.5"
    },
    "RSA private key": "-----BEGIN RSA PRIVATE KEY-----",
    "SSH (DSA) private key": "-----BEGIN DSA PRIVATE KEY-----",
    "SSH (EC) private key": "-----BEGIN EC PRIVATE KEY-----",
    "PGP private key block": "-----BEGIN PGP PRIVATE KEY BLOCK-----",
    "Amazon AWS Access Key ID": {
        "pattern": "AKIA[0-9A-Z]{16}",
        "entropy": true
    },
    "Amazon MWS Auth Token": {
        "pattern": "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
        "enropy": true
    },
    "AWS API Key": {
        "pattern": "AKIA[0-9A-Z]{16}",
        "entropy": true
    },
    "GitHub": {
        "pattern": "(?i)(github|access[[:punct:]]token)[\\s[[:punct:]]]{1,4}[0-9a-zA-Z]{35,40}",
        "entropy": true,
        "threshold": "4.5"
    },
    "Generic API Key": {
        "pattern": "(?i)(api|access)[\\s[[:punct:]]]?key[\\s[[:punct:]]]{1,4}[0-9a-zA-Z\\-_]{16,64}[\\s[[:punct:]]]?",
        "entropy": true
    },
    "Generic Account API Key": {
        "pattern": "(?i)account[\\s[[:punct:]]]?api[\\s[[:punct:]]]{1,4}[0-9a-zA-Z\\-_]{16,64}[\\s[[:punct:]]]?",
        "entropy": true
    },
    "Generic Secret": {
        "pattern" : "(?i)secret[\\s[[:punct:]]]{1,4}[0-9a-zA-Z-_]{16,64}[\\s[[:punct:]]]?",
        "entropy": true
    },
    "Google API Key": {
        "pattern": "AIza[0-9A-Za-z\\-_]{35}",
        "entropy": true
    },
    "Google Cloud Platform API Key": {
        "pattern": "AIza[0-9A-Za-z\\-_]{35}",
        "entropy": true
    },
    "Google Cloud Platform OAuth": "(?i)[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com",
    "Google Drive API Key": {
        "pattern": "AIza[0-9A-Za-z\\-_]{35}",
        "entropy": true
    },
    "Google Drive OAuth": "(?i)[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com",
    "Google (GCP) Service-account": {
        "pattern": "(?i)\"type\": \"service_account\"",
        "entropy": true
    },
    "Google Gmail API Key": {
        "pattern": "AIza[0-9A-Za-z\\-_]{35}",
        "entropy": true
    },
    "Google Gmail OAuth": "(?i)[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com",
    "Google OAuth Access Token": {
        "pattern": "ya29\\.[0-9A-Za-z\\-_]+",
        "entropy": true
    },
    "Credentials in absolute URL": "(?i)((https?|ftp)://)(([a-z0-9$_\\.\\+!\\*'\\(\\),;\\?&=-]|%[0-9a-f]{2})+(:([a-z0-9$_\\.\\+!\\*'\\(\\),;\\?&=-]|%[0-9a-f]{2})+)?@)((([a-z0-9]\\.|[a-z0-9][a-z0-9-]*[a-z0-9]\\.)*[a-z][a-z0-9-]*[a-z0-9]|((\\d|[1-9]\\d|1\\d{2}|2[0-4][0-9]|25[0-5])\\.){3}(\\d|[1-9]\\d|1\\d{2}|2[0-4][0-9]|25[0-5]))(:\\d+)?)(((/+([a-z0-9$_\\.\\+!\\*'\\(\\),;:@&=-]|%[0-9a-f]{2})*)*(\\?([a-z0-9$_\\.\\+!\\*'\\(\\),;:@&=-]|%[0-9a-f]{2})*)?)?)?",
    "Slack Webhook": "(?i)https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
}

```
The entropy is calculated for each word of a matched text considering only the word with the maximum entropy. The findings with an entropy lower than the threshold are filtered out.

This allow us to remove many false positives which are for instance only
paths in a secrets manager.

This changes are backward compatible with the old regex definition.

### CODE REVIEW

**Comment by ccojocar** [comment]
@cutler-scott-newrelic I would really appreciate if we could get a review on this pull request. Thank you in advance!

**Comment by cutler-scott-newrelic** [comment]
Hi @ccojocar , thanks for the PR! I will try to get to this today or tomorrow. I was out on vacation over the last few days.

**Comment by ccojocar** [comment]
@cutler-scott-newrelic Thanks for merging the other 2 PRs! This one is now rebased and ready for review. Thanks again!

**Comment by cutler-scott-newrelic** [comment]
Hi @ccojocar ! So I took a look at this really like it, and appreciate the huge lift in changing the regex file format while keeping it backwards compatible. To be honest I was working on this same problem with a different motivation, but was stuck. Now that you solved it I plan on making your data types a little more agnostic in the future so I can add a few more fields. 

Another note is that it looks like your choice in making a new calc_shannon_entropy function was smart, I see my error now in calc_entropy (my misunderstanding of the algorithm) and plan on fixing that in the near future as well.

**Pull request merged**
