### PR TITLE
Add a Dockerfile to build and run the rusty-hog scanners

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by ccojocar** [comment]
@cutler-scott-newrelic It would be great if you could have a look also over this Dockerfile. Thanks!

**Comment by ccojocar** [comment]
1. This is right, the openssl library is dynamically loaded therefore it doesn't need to be added to the build container. 

2. I made the hog binary configurable in the docker image entry point. Unfortunately it requires a custom entrypoint script in order to achieve this, but now it can be built for various hogs as follows:
```
docker build -t rusty-hog --build-arg HOG=berkshire .
```

Does these address your concerns?

**Comment by ccojocar** [comment]
The image can be run with this command:
```
docker run -it --rm rusty-hog --help
```
it should print the helper of the hog used as an entry point, something like:
```
+ /usr/local/bin/berkshire_hog --help
berkshire_hog 1.0.4
Scott Cutler <scutler@newrelic.com>
S3 secret hunter in Rust. Avoid bandwidth costs, run this within a VPC!

USAGE:
    berkshire_hog [FLAGS] [OPTIONS] <S3URI> <S3REGION>

....
```

**Comment by cutler-scott-newrelic** [comment]
That works for me. I'll review and merge it around 11am my time in Portland
OR.

**Comment by ccojocar** [comment]
Thanks! No rush.

**Pull request merged**
